server:
  port: 80

spring:
  application:
    name: cloud-consumer-order
  cloud:
  #注册到zookeeper地址
    zookeeper:
      #这里的ip是linux服务器ip 端口2181是zookeeper的默认端口号  多个服务时和eureka一样地址用逗号“,”隔开
      connect-string: 192.168.182.129:2181



